<a href="https://colab.research.google.com/github/xztema0207/xztema/blob/master/P_Pytorch_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch
import torch as trx

In [0]:
!pwd

/content


In [0]:
arr = [[1,2], [3,4]]
arr

[[1, 2], [3, 4]]

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [0]:
import torch

In [0]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [0]:
np.ones((2,2))
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [0]:
np.random.rand(2,2)
torch.rand(2,2)

tensor([[0.7147, 0.7616],
        [0.8708, 0.4534]])

In [0]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [0]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [0]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [0]:
if torch.cuda.is_available():
  torch.cuda.manual_seed(0)

In [0]:
torch.cuda.is_available()

True

In [0]:
!nvidia-smi

Sat Oct  5 15:42:41 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    27W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

## Numpy to Torch

In [0]:
np_arr = np.ones((2,2))
np_arr

array([[1., 1.],
       [1., 1.]])

In [0]:
torch_tensor = torch.from_numpy(np_arr)
torch_tensor

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [0]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [0]:
np_arr2 = np.ones((2,2), dtype=np.int8)
torch.from_numpy(np_arr2)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

## Torch to Numpy

In [0]:
tc_tensor = torch.ones(2,2)
np_arr3 = tc_tensor.numpy()

In [0]:
type(np_arr3)
np_arr3

array([[1., 1.],
       [1., 1.]], dtype=float32)

## CPU vs GPU

In [0]:
t_cpu =trx.ones(2,2)

In [0]:
if torch.cuda.is_available():
  t_cpu.cuda()
t_cpu

tensor([[1., 1.],
        [1., 1.]])

In [0]:
t_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

In [0]:
next(t_cpu).is_cuda()

TypeError: ignored

In [0]:
t_cpu.size()

torch.Size([2, 2])

In [0]:
t_cpu.view(4)

tensor([1., 1., 1., 1.])

In [0]:
a = torch.ones(2,2)
a.view(4)

tensor([1., 1., 1., 1.])

## Element-wise Addition

In [0]:
a = torch.ones(2,2)
b = torch.ones(2,2)
c = a+b
d = torch.add(a,b)
print(c)
print(d)

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [0]:
c.add(a)
c.add_(a)
c1= c.add(a)

print(c, c1)

tensor([[7., 7.],
        [7., 7.]]) tensor([[8., 8.],
        [8., 8.]])


In [0]:
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [0]:
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [0]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

print(a*b)
c=torch.mul(a,b)
d=a.mul(b)
print("a:", a)
d1 = a.mul_(b)
print("a:", a)

tensor([[0., 0.],
        [0., 0.]])
a: tensor([[1., 1.],
        [1., 1.]])
a: tensor([[0., 0.],
        [0., 0.]])


In [0]:
a = torch.ones(2,2)
b = torch.ones(2,2)*3
a/b
torch.div(a,b)
a.div_(b)
a

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

## Tensor Mean

In [0]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [0]:
a.mean(dim=0)

tensor(5.5000)

In [0]:
a.mean(dim=1)

IndexError: ignored

In [0]:
b = torch.Tensor([[1,2,3,4,5,6,7,8,9,10], [1,2,3,4,5,6,7,8,9,10]])
b.size()

torch.Size([2, 10])

In [0]:
b.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
b.mean(dim=1)

tensor([5.5000, 5.5000])

In [0]:
a.std(dim=0)

tensor(3.0277)

In [0]:
b.std(dim=1)

tensor([3.0277, 3.0277])

In [0]:
!nvidia-smi

Sun Oct  6 03:17:34 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8    29W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  